//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public int Id { get; set; }
        public string ContainerID { get; set; }
        public string ContainerOutDate { get; set; }
        public string Status { get; set; }
        public string Weight { get; set; }
        public string Destination { get; set; }
    }
}
